name: "The Auditor PR Reviewer"
description: "Automatically audits Solidity, Move, and Rust smart contracts on every PR using Slither, Aderyn, Cargo-Audit, and Gemini"
author: "Shawnchee"

branding:
  icon: "shield"
  color: "blue"

inputs:
  gemini_api_key:
    description: "Google Gemini API key for AI-powered analysis."
    required: true

  gemini_model:
    description: "Gemini model to use for analysis."
    required: false
    default: "gemini-2.5-flash"

  github_token:
    description: "GitHub token for posting PR review comments. Defaults to the automatic GITHUB_TOKEN."
    required: false
    default: ${{ github.token }}

  slither_args:
    description: "Additional arguments to pass to Slither (e.g., '--exclude naming-convention')."
    required: false
    default: ""

  aderyn_args:
    description: "Additional arguments to pass to Aderyn."
    required: false
    default: ""

  cargo_audit_args:
    description: "Additional arguments to pass to cargo-audit."
    required: false
    default: ""

  severity_threshold:
    description: "Minimum severity to report: 'low', 'medium', 'high', or 'critical'."
    required: false
    default: "low"

  fail_on_findings:
    description: "If 'true', the action will exit with a non-zero code when vulnerabilities are found."
    required: false
    default: "false"

  custom_prompt:
    description: "Optional additional instructions for the Gemini AI reviewer (e.g., 'Focus on reentrancy and access control')."
    required: false
    default: ""

  include_paths:
    description: "Comma-separated glob patterns of paths to include (e.g., 'contracts/**,src/**'). Defaults to all supported files."
    required: false
    default: ""

  exclude_paths:
    description: "Comma-separated glob patterns of paths to exclude (e.g., 'test/**,mocks/**')."
    required: false
    default: ""

outputs:
  vulnerability_count:
    description: "Total number of vulnerabilities found across all tools and chains."
    value: ${{ steps.audit.outputs.vulnerability_count }}

  critical_count:
    description: "Number of critical-severity findings."
    value: ${{ steps.audit.outputs.critical_count }}

  high_count:
    description: "Number of high-severity findings."
    value: ${{ steps.audit.outputs.high_count }}

  medium_count:
    description: "Number of medium-severity findings."
    value: ${{ steps.audit.outputs.medium_count }}

  low_count:
    description: "Number of low/informational findings."
    value: ${{ steps.audit.outputs.low_count }}

  security_score:
    description: "Overall security score from 0-100 calculated by PR Auditor."
    value: ${{ steps.audit.outputs.security_score }}

  report_url:
    description: "URL of the posted PR review comment (if applicable)."
    value: ${{ steps.audit.outputs.report_url }}

runs:
  using: "composite"
  steps:
    # ── Step 1: Install Python + Slither ───────────────────
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"

    - name: Install Slither & solc
      shell: bash
      run: |
        pip install --quiet slither-analyzer solc-select
        solc-select install 0.8.28 && solc-select use 0.8.28

    # ── Step 2: Install Aderyn (official installer) ──────────
    - name: Install Aderyn
      shell: bash
      run: |
        echo "Installing Aderyn via official installer..."
        curl --proto '=https' --tlsv1.2 -LsSf https://github.com/cyfrin/aderyn/releases/download/aderyn-v0.6.8/aderyn-installer.sh | sh
        echo "$HOME/.cargo/bin" >> $GITHUB_PATH
        echo "Aderyn installed: $(aderyn --version 2>/dev/null || echo 'will be available in next step')"

    # ── Step 3: Install cargo-audit (pre-built) ────────────
    - name: Install cargo-audit
      shell: bash
      run: |
        CARGO_AUDIT_VERSION="0.21.1"
        echo "Downloading cargo-audit v${CARGO_AUDIT_VERSION}..."
        curl -sL "https://github.com/rustsec/rustsec/releases/download/cargo-audit%2Fv${CARGO_AUDIT_VERSION}/cargo-audit-x86_64-unknown-linux-musl-v${CARGO_AUDIT_VERSION}.tgz" | tar xz -C /tmp
        mv /tmp/cargo-audit-x86_64-unknown-linux-musl-v${CARGO_AUDIT_VERSION}/cargo-audit /usr/local/bin/cargo-audit
        chmod +x /usr/local/bin/cargo-audit
        echo "cargo-audit installed: $(cargo-audit --version)"

    # ── Step 4: Install jq (usually pre-installed) ─────────
    - name: Ensure jq is available
      shell: bash
      run: |
        if ! command -v jq &> /dev/null; then
          sudo apt-get update && sudo apt-get install -y jq
        fi

    # ── Step 5: Run the audit ──────────────────────────────
    - name: Run PR Auditor
      id: audit
      shell: bash
      env:
        INPUT_GEMINI_API_KEY: ${{ inputs.gemini_api_key }}
        INPUT_GITHUB_TOKEN: ${{ inputs.github_token }}
        INPUT_GEMINI_MODEL: ${{ inputs.gemini_model }}
        INPUT_SLITHER_ARGS: ${{ inputs.slither_args }}
        INPUT_ADERYN_ARGS: ${{ inputs.aderyn_args }}
        INPUT_CARGO_AUDIT_ARGS: ${{ inputs.cargo_audit_args }}
        INPUT_SEVERITY_THRESHOLD: ${{ inputs.severity_threshold }}
        INPUT_FAIL_ON_FINDINGS: ${{ inputs.fail_on_findings }}
        INPUT_CUSTOM_PROMPT: ${{ inputs.custom_prompt }}
        INPUT_INCLUDE_PATHS: ${{ inputs.include_paths }}
        INPUT_EXCLUDE_PATHS: ${{ inputs.exclude_paths }}
        SCRIPTS_DIR: ${{ github.action_path }}/scripts
      run: |
        chmod +x ${{ github.action_path }}/entrypoint.sh ${{ github.action_path }}/scripts/*.sh
        bash ${{ github.action_path }}/entrypoint.sh
