name: "The Auditor PR Reviewer"
description: "Automatically audits Solidity, Move, and Rust smart contracts on every PR using Slither, Aderyn, Cargo-Audit, and Gemini"
author: "Shawnchee"

branding:
  icon: "shield"
  color: "blue"

inputs:
  gemini_api_key:
    description: "Google Gemini API key for AI-powered analysis."
    required: true

  gemini_model:
    description: "Gemini model to use for analysis."
    required: false
    default: "gemini-2.5-flash"

  github_token:
    description: "GitHub token for posting PR review comments. Defaults to the automatic GITHUB_TOKEN."
    required: false
    default: ${{ github.token }}

  slither_args:
    description: "Additional arguments to pass to Slither (e.g., '--exclude naming-convention')."
    required: false
    default: ""

  aderyn_args:
    description: "Additional arguments to pass to Aderyn."
    required: false
    default: ""

  cargo_audit_args:
    description: "Additional arguments to pass to cargo-audit."
    required: false
    default: ""

  severity_threshold:
    description: "Minimum severity to report: 'low', 'medium', 'high', or 'critical'."
    required: false
    default: "low"

  fail_on_findings:
    description: "If 'true', the action will exit with a non-zero code when there are HIGH or CRITICAL vulnerabilities."
    required: false
    default: "true"

  custom_prompt:
    description: "Optional additional instructions for the Gemini AI reviewer (e.g., 'Focus on reentrancy and access control')."
    required: false
    default: ""

  include_paths:
    description: "Comma-separated glob patterns of paths to include (e.g., 'contracts/**,src/**'). Defaults to all supported files."
    required: false
    default: ""

  exclude_paths:
    description: "Comma-separated glob patterns of paths to exclude (e.g., 'test/**,mocks/**')."
    required: false
    default: ""

  include_raw_output:
    description: "If 'true', posts a second PR comment with the raw unprocessed output from Slither, Aderyn, and cargo-audit."
    required: false
    default: "false"

outputs:
  vulnerability_count:
    description: "Total number of vulnerabilities found across all tools and chains."
    value: ${{ steps.audit.outputs.vulnerability_count }}

  critical_count:
    description: "Number of critical-severity findings."
    value: ${{ steps.audit.outputs.critical_count }}

  high_count:
    description: "Number of high-severity findings."
    value: ${{ steps.audit.outputs.high_count }}

  medium_count:
    description: "Number of medium-severity findings."
    value: ${{ steps.audit.outputs.medium_count }}

  low_count:
    description: "Number of low/informational findings."
    value: ${{ steps.audit.outputs.low_count }}

  security_score:
    description: "Overall security score from 0-100 calculated by PR Auditor."
    value: ${{ steps.audit.outputs.security_score }}

  report_url:
    description: "URL of the posted PR review comment (if applicable)."
    value: ${{ steps.audit.outputs.report_url }}

runs:
  using: "composite"
  steps:
    # ── Step 1: Install Python + Slither ───────────────────
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"

    - name: Install Slither & solc
      shell: bash
      run: |
        pip install --quiet slither-analyzer solc-select
        solc-select install 0.8.28 && solc-select use 0.8.28

    # ── Step 2: Install Aderyn (official installer) ──────────
    - name: Install Aderyn
      shell: bash
      run: |
        echo "Installing Aderyn via official installer..."
        curl --proto '=https' --tlsv1.2 -LsSf https://github.com/cyfrin/aderyn/releases/download/aderyn-v0.6.8/aderyn-installer.sh | sh
        echo "$HOME/.cargo/bin" >> $GITHUB_PATH
        echo "Aderyn installed: $(aderyn --version 2>/dev/null || echo 'will be available in next step')"

    # ── Step 3: Install cargo-audit (pre-built) ────────────
    - name: Install cargo-audit
      shell: bash
      run: |
        CARGO_AUDIT_VERSION="0.21.1"
        echo "Downloading cargo-audit v${CARGO_AUDIT_VERSION}..."
        curl -sL "https://github.com/rustsec/rustsec/releases/download/cargo-audit%2Fv${CARGO_AUDIT_VERSION}/cargo-audit-x86_64-unknown-linux-musl-v${CARGO_AUDIT_VERSION}.tgz" | tar xz -C /tmp
        mv /tmp/cargo-audit-x86_64-unknown-linux-musl-v${CARGO_AUDIT_VERSION}/cargo-audit /usr/local/bin/cargo-audit
        chmod +x /usr/local/bin/cargo-audit
        echo "cargo-audit installed: $(cargo-audit --version)"

    # ── Step 4: Install jq (usually pre-installed) ─────────
    - name: Ensure jq is available
      shell: bash
      run: |
        if ! command -v jq &> /dev/null; then
          sudo apt-get update && sudo apt-get install -y jq
        fi

    # ── Step 5: Run the audit ──────────────────────────────
    - name: Run PR Auditor
      id: audit
      shell: bash
      env:
        INPUT_GEMINI_API_KEY: ${{ inputs.gemini_api_key }}
        INPUT_GITHUB_TOKEN: ${{ inputs.github_token }}
        INPUT_GEMINI_MODEL: ${{ inputs.gemini_model }}
        INPUT_SLITHER_ARGS: ${{ inputs.slither_args }}
        INPUT_ADERYN_ARGS: ${{ inputs.aderyn_args }}
        INPUT_CARGO_AUDIT_ARGS: ${{ inputs.cargo_audit_args }}
        INPUT_SEVERITY_THRESHOLD: ${{ inputs.severity_threshold }}
        INPUT_FAIL_ON_FINDINGS: ${{ inputs.fail_on_findings }}
        INPUT_CUSTOM_PROMPT: ${{ inputs.custom_prompt }}
        INPUT_INCLUDE_PATHS: ${{ inputs.include_paths }}
        INPUT_EXCLUDE_PATHS: ${{ inputs.exclude_paths }}
        SCRIPTS_DIR: ${{ github.action_path }}/scripts
      run: |
        chmod +x ${{ github.action_path }}/entrypoint.sh ${{ github.action_path }}/scripts/*.sh
        bash ${{ github.action_path }}/entrypoint.sh

    # ── Step 6 (Optional): Post raw tool output ────────────
    - name: Post Raw Tool Output
      if: inputs.include_raw_output == 'true' && always()
      shell: bash
      env:
        GH_TOKEN: ${{ inputs.github_token }}
      run: |
        echo "Collecting raw tool output..."
        TMP_BODY=$(mktemp /tmp/raw-body-XXXX.txt)

        printf '## 🔬 Raw Static Analysis Output\n\n' >> "$TMP_BODY"
        printf '*Unprocessed output from the analysis tools.*\n\n' >> "$TMP_BODY"

        # Slither raw — use head directly (avoids SIGPIPE with pipefail)
        if [ -f /tmp/auditor-reports/slither.json ]; then
          printf '<details>\n<summary>🐍 Slither Raw Output</summary>\n\n```json\n' >> "$TMP_BODY"
          head -c 30000 /tmp/auditor-reports/slither.json >> "$TMP_BODY" || true
          printf '\n```\n</details>\n\n' >> "$TMP_BODY"
        else
          printf '**Slither:** No output or not applicable.\n\n' >> "$TMP_BODY"
        fi

        # Aderyn raw
        if [ -f /tmp/auditor-reports/aderyn.json ]; then
          printf '<details>\n<summary>🦅 Aderyn Raw Output</summary>\n\n```json\n' >> "$TMP_BODY"
          head -c 30000 /tmp/auditor-reports/aderyn.json >> "$TMP_BODY" || true
          printf '\n```\n</details>\n\n' >> "$TMP_BODY"
        else
          printf '**Aderyn:** No output or not applicable.\n\n' >> "$TMP_BODY"
        fi

        # cargo-audit raw
        if [ -f /tmp/auditor-reports/cargo_audit.json ]; then
          printf '<details>\n<summary>🦀 cargo-audit Raw Output</summary>\n\n```json\n' >> "$TMP_BODY"
          head -c 30000 /tmp/auditor-reports/cargo_audit.json >> "$TMP_BODY" || true
          printf '\n```\n</details>\n\n' >> "$TMP_BODY"
        else
          printf '**cargo-audit:** No output or not applicable.\n\n' >> "$TMP_BODY"
        fi

        printf '\n---\n*Generated by [PR Auditor](https://github.com/Shawnchee/the-auditor) 🔬 — Raw Tool Output*\n' >> "$TMP_BODY"

        # Post to PR — use --rawfile to avoid arg list too long
        if [ -n "${GITHUB_EVENT_PATH:-}" ]; then
          PR_NUMBER=$(jq -r '.pull_request.number // .number // empty' "$GITHUB_EVENT_PATH" 2>/dev/null || true)
          if [ -n "$PR_NUMBER" ]; then
            PAYLOAD=$(jq -n --rawfile body "$TMP_BODY" '{"body": $body}')
            curl -s -X POST \
              -H "Authorization: token $GH_TOKEN" \
              -H "Accept: application/vnd.github.v3+json" \
              -d "$PAYLOAD" \
              "https://api.github.com/repos/${GITHUB_REPOSITORY}/issues/${PR_NUMBER}/comments" > /dev/null
            echo "Raw output posted to PR #${PR_NUMBER}"
          fi
        else
          cat "$TMP_BODY"
        fi
        rm -f "$TMP_BODY"
