#!/usr/bin/env bash

# function: builds a concise markdown summary from raw tool output files
# and posts it as a PR comment (instead of dumping raw JSON)

post_raw_summary() {
  local github_token="$1"
  local report_dir="${2:-/tmp/auditor-reports}"

  local TMP_BODY
  TMP_BODY=$(mktemp /tmp/raw-body-XXXX.txt)

  cat > "$TMP_BODY" <<'EOF'
## Raw Tool Output Summary

*Parsed summaries from each analysis tool. See the AI-reviewed report above for detailed analysis.*

EOF

  # ── Slither summary ──────────────────────────────
  if [ -f "$report_dir/slither.json" ]; then
    local TOTAL HIGH MED LOW
    TOTAL=$(jq '[.results.detectors // [] | length] | add // 0' "$report_dir/slither.json" 2>/dev/null || echo 0)
    HIGH=$(jq '[.results.detectors[]? | select(.impact == "High")] | length' "$report_dir/slither.json" 2>/dev/null || echo 0)
    MED=$(jq '[.results.detectors[]? | select(.impact == "Medium")] | length' "$report_dir/slither.json" 2>/dev/null || echo 0)
    LOW=$(jq '[.results.detectors[]? | select(.impact == "Low" or .impact == "Informational")] | length' "$report_dir/slither.json" 2>/dev/null || echo 0)

    printf '### 🐍 Slither\n\n' >> "$TMP_BODY"
    printf '**%s findings** — 🔴 High: %s · 🟡 Medium: %s · 🔵 Low/Info: %s\n\n' "$TOTAL" "$HIGH" "$MED" "$LOW" >> "$TMP_BODY"

    if [ "$TOTAL" -gt 0 ] 2>/dev/null; then
      printf '| Impact | Detector | Description |\n' >> "$TMP_BODY"
      printf '|--------|----------|-------------|\n' >> "$TMP_BODY"
      jq -r '.results.detectors[]? | "| \(.impact) | `\(.check)` | \(.description | split("\n")[0] | .[0:100]) |"' \
        "$report_dir/slither.json" 2>/dev/null | head -30 >> "$TMP_BODY" || true
      printf '\n\n' >> "$TMP_BODY"
    fi
  else
    printf '### 🐍 Slither\n\nNo output or not applicable.\n\n' >> "$TMP_BODY"
  fi

  # ── Aderyn summary ───────────────────────────────
  if [ -f "$report_dir/aderyn.json" ]; then
    local HIGH_A LOW_A TOTAL_A
    HIGH_A=$(jq '.high_issues.issues // [] | length' "$report_dir/aderyn.json" 2>/dev/null || echo 0)
    LOW_A=$(jq '.low_issues.issues // [] | length' "$report_dir/aderyn.json" 2>/dev/null || echo 0)
    TOTAL_A=$((HIGH_A + LOW_A))

    printf '### 🦅 Aderyn\n\n' >> "$TMP_BODY"
    printf '**%s findings** — 🔴 High: %s · 🔵 Low: %s\n\n' "$TOTAL_A" "$HIGH_A" "$LOW_A" >> "$TMP_BODY"

    if [ "$TOTAL_A" -gt 0 ] 2>/dev/null; then
      printf '| Severity | Title | Instances |\n' >> "$TMP_BODY"
      printf '|----------|-------|-----------|\n' >> "$TMP_BODY"
      jq -r '.high_issues.issues[]? | "| 🔴 High | \(.title) | \(.instances | length) |"' \
        "$report_dir/aderyn.json" 2>/dev/null >> "$TMP_BODY" || true
      jq -r '.low_issues.issues[]? | "| 🔵 Low | \(.title) | \(.instances | length) |"' \
        "$report_dir/aderyn.json" 2>/dev/null >> "$TMP_BODY" || true
      printf '\n\n' >> "$TMP_BODY"
    fi
  else
    printf '### 🦅 Aderyn\n\nNo output or not applicable.\n\n' >> "$TMP_BODY"
  fi

  # ── cargo-audit summary ──────────────────────────
  if [ -f "$report_dir/cargo_audit.json" ]; then
    local VULNS NOTES
    VULNS=$(jq '[.audits[]?.vulnerabilities.list // [] | length] | add // 0' "$report_dir/cargo_audit.json" 2>/dev/null || echo 0)
    NOTES=$(jq '.notes // [] | length' "$report_dir/cargo_audit.json" 2>/dev/null || echo 0)

    printf '### 🦀 cargo-audit\n\n' >> "$TMP_BODY"
    printf '**%s vulnerabilities found**' "$VULNS" >> "$TMP_BODY"
    [ "$NOTES" -gt 0 ] 2>/dev/null && printf ' · ⚠️ %s notes' "$NOTES" >> "$TMP_BODY"
    printf '\n\n' >> "$TMP_BODY"

    if [ "$VULNS" -gt 0 ] 2>/dev/null; then
      printf '| Advisory | Crate | Patched |\n' >> "$TMP_BODY"
      printf '|----------|-------|---------|\n' >> "$TMP_BODY"
      jq -r '.audits[]?.vulnerabilities.list[]? | "| \(.advisory.id) | `\(.package.name)` \(.package.version) | \(.versions.patched // ["N/A"] | join(", ")) |"' \
        "$report_dir/cargo_audit.json" 2>/dev/null | head -20 >> "$TMP_BODY" || true
      printf '\n\n' >> "$TMP_BODY"
    fi

    if [ "$NOTES" -gt 0 ] 2>/dev/null; then
      jq -r '.notes[]? | "> ⚠️ **\(.status)**: \(.note // .error)"' \
        "$report_dir/cargo_audit.json" 2>/dev/null >> "$TMP_BODY" || true
      printf '\n' >> "$TMP_BODY"
    fi
  else
    printf '### 🦀 cargo-audit\n\nNo output or not applicable.\n\n' >> "$TMP_BODY"
  fi

  printf '\n---\n*Generated by [PR Auditor](https://github.com/Shawnchee/the-auditor) 🔬 — Raw Tool Summary*\n' >> "$TMP_BODY"

  # ── Post to PR ──────────────────────────────────────
  if [ -n "${GITHUB_EVENT_PATH:-}" ]; then
    local PR_NUMBER
    PR_NUMBER=$(jq -r '.pull_request.number // .number // empty' "$GITHUB_EVENT_PATH" 2>/dev/null || true)
    if [ -n "$PR_NUMBER" ]; then
      local PAYLOAD HTTP_CODE
      PAYLOAD=$(jq -n --rawfile body "$TMP_BODY" '{"body": $body}')
      HTTP_CODE=$(curl -sS -o /tmp/raw-post-response.json -w "%{http_code}" -X POST \
        -H "Authorization: token $github_token" \
        -H "Accept: application/vnd.github.v3+json" \
        -d "$PAYLOAD" \
        "https://api.github.com/repos/${GITHUB_REPOSITORY}/issues/${PR_NUMBER}/comments")
      if [ "$HTTP_CODE" = "201" ]; then
        echo "[PR Auditor] Raw tool summary posted to PR #${PR_NUMBER}"
      else
        echo "::warning::Failed to post raw summary comment (HTTP $HTTP_CODE)"
        cat /tmp/raw-post-response.json >&2 || true
      fi
      rm -f /tmp/raw-post-response.json
    fi
  else
    cat "$TMP_BODY"
  fi
  rm -f "$TMP_BODY"
}
